### ISSUE TITLE
Error: CallManager.set_result()

### ISSUE THREAD

**Issue by redjoe** [gawel/panoramisk#35]
I try to run originate.py script (python 3.4, panoramisk 1.1.dev) on asterisk 11.21 and get error:
```
Exception in callback CallManager.set_result(<Future pendi...sk._wakeup()]>)(<Future finis...' content=''>>)
handle: <Handle CallManager.set_result(<Future pendi...sk._wakeup()]>)(<Future finis...' content=''>>)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.4/dist-packages/panoramisk-1.1.dev0-py3.4.egg/panoramisk/call_manager.py", line 32, in set_result
    event = result.result()[-1]
  File "/usr/local/lib/python3.4/dist-packages/panoramisk-1.1.dev0-py3.4.egg/panoramisk/utils.py", line 191, in __getitem__
    return self._store[key.lower()][1]
AttributeError: 'int' object has no attribute 'lower'
```

**Comment by gawel** [comment]
Just commit a quick fix: https://github.com/gawel/panoramisk/commit/2f0226f603121119a74db049789358c16b5a11cd

But I guess the problem is more in your call

Try to provide your call and the asterisk stream if you still encounter a problem

**Comment by redjoe** [comment]
Thank you very much. Problem solved. It's so shame, but error was in spelling value of 'Context' parameter while sending to AMI.
