### ISSUE TITLE
failed in originate

### ISSUE THREAD

**Issue by paketecuento** [gawel/panoramisk#64]
Hi, I tested your originate.py sample. If the call is answered, everything is fine, but if no answer or busy, then I get

````
Exception in callback CallManager.set_result(<Future pendi...3e380c828>()]>)(<Future finis... content=''>]>)
handle: <Handle CallManager.set_result(<Future pendi...3e380c828>()]>)(<Future finis... content=''>]>)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/panoramisk/call_manager.py", line 37, in set_result
    call = self.calls_queues[uniqueid]
KeyError: '<null>'
```

Maybe the problem is related to `call_manager.py`

**Comment by paketecuento** [comment]
yeah!! sorry to bother
