### ISSUE TITLE
Error after callee answer

### ISSUE THREAD

**Issue by morfair** [gawel/panoramisk#90]
Python 3.7
call = await _AMI_MANAGER.send_action({...})

```
DEBUG:panoramisk.manager:message interpreted: <Message ActionID='action/0db9ad0a-4f02-4cb2-b8e3-65b78ff88291/1/7' Message='Originate successfully queued' Response='Success' content=''>
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <panoramisk.ami_protocol.AMIProtocol object at 0x7f26e91954a8>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 824, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.7/site-packages/panoramisk/ami_protocol.py", line 72, in data_received
    self.handle_message(message)
  File "/usr/local/lib/python3.7/site-packages/panoramisk/ami_protocol.py", line 79, in handle_message
    if response.add_message(message):
  File "/usr/local/lib/python3.7/site-packages/panoramisk/actions.py", line 88, in add_message
    multi = self.multi
  File "/usr/local/lib/python3.7/site-packages/panoramisk/actions.py", line 69, in multi
    elif msg.endswith('successfully queued') and self['async'] != 'false':
  File "/usr/local/lib/python3.7/site-packages/panoramisk/utils.py", line 179, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'async'
ERROR:panoramisk.manager:Connection lost
INFO:panoramisk.manager:Try to connect again in 2 seconds
```

**Comment by romkazor** [comment]
show full await _AMI_MANAGER.send_action({...})

**Comment by morfair** [comment]
@romkazor 
```
call = await _AMI_MANAGER.send_action({
 "Action": "Originate",
 "Channel": f"Local/{number}@pstn",
 "Context": "deptors_calling",
 "Exten": "say",
 "Priority": 1,
 "CallerID": cid,
 "Timeout": CALL_TIMEOUT,
 "Variable": f"debt={debt}",
})
```

**Comment by romkazor** [comment]
try to add 'Async': 'true'
