### ISSUE TITLE
error using for playDTMF

### ISSUE THREAD

**Issue by starlessboi** [gawel/panoramisk#97]
Hi, I'm using this library for a while, thanks for your effort.
recently I tried using that for playing dtmf with action playDTMF
it plays beep sound but gives error as output, and code hangs, with this error:

Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib64/python3.6/asyncio/selector_events.py", line 721, in _read_ready
    self._protocol.data_received(data)
  File "/opt/qs_main/qs_mainenv/lib64/python3.6/site-packages/panoramisk/ami_protocol.py", line 72, in data_received
    self.handle_message(message)
  File "/opt/qs_main/qs_mainenv/lib64/python3.6/site-packages/panoramisk/ami_protocol.py", line 79, in handle_message
    if response.add_message(message):
  File "/opt/qs_main/qs_mainenv/lib64/python3.6/site-packages/panoramisk/actions.py", line 92, in add_message
    multi = self.multi
  File "/opt/qs_main/qs_mainenv/lib64/python3.6/site-packages/panoramisk/actions.py", line 71, in multi
    elif msg.endswith('successfully queued') and self['async'] != 'false':
  File "/opt/qs_main/qs_mainenv/lib64/python3.6/site-packages/panoramisk/utils.py", line 179, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'async'
 
would you please guide me through solving this issue?
thanks

**Comment by gawel** [comment]
Looks like duplicate https://github.com/gawel/panoramisk/pull/88
